[package]
name = "fxoanda_definitions"
version = "0.1.1"
authors = ["James McGill <jbmcgill@gmail.com>"]
edition = "2018"
description = "Library to conduct currency conversion with the Oanda API"
license = "MIT/Apache-2.0"

[dependencies]
serde_json = "1.0"
serde = "1.0.83"
serde_derive = "1.0.83"
chrono = {version = "0.4.6", features = ["serde"] }
time = "0.3.34"
fxoanda_serdes = {version="0.1.0", path = "../fxoanda_serdes/" }
